/* Copyright (c) 2013, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *  * Neither the name of The Linux Foundation nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS
 * OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED
 * AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_OTM1287A_YUSHUN_720P_VIDEO_H_

#define _PANEL_OTM1287A_YUSHUN_720P_VIDEO_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

#define MIPI_DSI_CMD_WAIT(cmd,ms) {sizeof(cmd), cmd, ms}


#if 0

typedef struct panel_config{

        char  *panel_node_id;
        char  *panel_controller;
        char  *panel_compatible;
        uint16_t panel_interface;
        uint16_t panel_type;
        char   *panel_destination;
        uint32_t panel_orientation;
        uint32_t panel_clockrate;
        uint16_t panel_framerate;
        uint16_t panel_channelid;
        uint16_t dsi_virtualchannel_id;
        uint16_t panel_broadcast_mode;
        uint16_t panel_lp11_init;
        uint16_t panel_init_delay;
        uint16_t dsi_stream;
        uint8_t  interleave_mode;
        uint32_t panel_bitclock_freq;
        uint32_t panel_operating_mode;
        uint32_t panel_with_enable_gpio;
        uint8_t  mode_gpio_state;
        char  *slave_panel_node_id;
};
#endif 

static struct panel_config otm1287a_yushun_720p_video_panel_data = {
  "qcom,mdss_dsi_otm1287a_yushun_720p_video", "dsi:0:", "qcom,mdss-dsi-panel",
  10, 0, "DISPLAY_1", 0, 0, 57, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};


#if 0
        uint16_t panel_width;
        uint16_t panel_height;
        uint16_t hfront_porch;
        uint16_t hback_porch;
        uint16_t hpulse_width;
        uint16_t hsync_skew;
        uint16_t vfront_porch;
        uint16_t vback_porch;
        uint16_t vpulse_width;
        uint16_t hleft_border;
        uint16_t hright_border;
        uint16_t vtop_border;
        uint16_t vbottom_border;
        uint16_t hactive_res;
        uint16_t vactive_res;
        uint16_t invert_data_polarity;
        uint16_t invert_vsync_polarity;
        uint16_t invert_hsync_polarity;
#endif 




static struct panel_resolution otm1287a_yushun_720p_video_panel_res = {
    // 720, 1280, 52, 100, 24, 0, 8, 40, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0
    1280, 720, 110, 220, 40, 0, 5, 20, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

static struct color_info otm1287a_yushun_720p_video_color = {
  24, 0, 0xff, 0, 0, 0
};

static char otm1287a_yushun_720p_video_on_cmd0[] = {
0x04, 0x00, 0x39, 0xC0,
0xB9, 0xFF, 0x83, 0x94,
};

static char otm1287a_yushun_720p_video_on_cmd1[] = {
0x07, 0x00, 0x39, 0xC0,
0xBA, 0x63, 0x03, 0x68,
0x6B, 0xB2, 0xC0, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd2[] = {
0x0B, 0x00, 0x39, 0xC0,
0xB1, 0x48, 0x12, 0x72,
0x09, 0x32, 0x44, 0x71,
0x31, 0x4F, 0x35, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd3[] = {
0x06, 0x00, 0x39, 0xC0,
0xB2, 0x00, 0x80, 0x64,
0x05, 0x07, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd4[] = {
				0x1F, 0x00, 0x39, 0xC0,
				0xB4, 0x26 ,0x76 ,0x26,
                                0x76, 0x26 ,0x26 ,0x05,
                                0x10, 0x86 ,0x35 ,0x00,
                                0x3F, 0x26 ,0x76 ,0x26,
                                0x76, 0x26 ,0x26 ,0x05,
                                0x10, 0x86 ,0x3F ,0x00,
                                0xFF, 0x81 ,0x81 ,0x81,
                                0x81, 0x08 ,0x01 ,0xff,

};

static char otm1287a_yushun_720p_video_on_cmd5[] = {
				0x22, 0x00, 0x39, 0xC0,
				0xD3 ,0x00 ,0x00 ,0x0F,
                                0x0F ,0x01 ,0x01 ,0x10,
                                0x10 ,0x32 ,0x10 ,0x00,
                                0x00 ,0x00 ,0x32 ,0x15,
                                0x04 ,0x05 ,0x04 ,0x32,
                                0x15 ,0x14 ,0x05 ,0x14,
                                0x37 ,0x33 ,0x04 ,0x04,
                                0x37 ,0x00 ,0x00 ,0x47,
                                0x05 ,0x40 ,0xff ,0xff,

};

static char otm1287a_yushun_720p_video_on_cmd6[] = {
				0x2D, 0x00, 0x39, 0xC0,
				0xD5,0x18 ,0x18 ,0x25 ,
                                0x24,0x27 ,0x26 ,0x11 ,
                                0x10,0x15 ,0x14 ,0x13 ,
                                0x12,0x17 ,0x16 ,0x01 ,
                                0x00,0x18 ,0x18 ,0x18 ,
                                0x18,0x18 ,0x18 ,0x18 ,
                                0x18,0x18 ,0x18 ,0x05 ,
                                0x04,0x03 ,0x02 ,0x07 ,
                                0x06,0x18 ,0x18 ,0x18 ,
                                0x18,0x21 ,0x20 ,0x23 ,
                                0x22,0x18 ,0x18 ,0x18 ,
                                0x18,0xff ,0xff ,0xff ,
};

static char otm1287a_yushun_720p_video_on_cmd7[] = {
				0x2D, 0x00, 0x39, 0xC0,
				0xD6, 0x18, 0x18 ,0x22,
                                0x23, 0x20, 0x21 ,0x12,
                                0x13, 0x16, 0x17 ,0x10,
                                0x11, 0x14, 0x15 ,0x06,
                                0x07, 0x18, 0x18 ,0x18,
                                0x18, 0x18, 0x18 ,0x18,
                                0x18, 0x18, 0x18 ,0x02,
                                0x03, 0x04, 0x05 ,0x00,
                                0x01, 0x18, 0x18 ,0x18,
                                0x18, 0x26, 0x27 ,0x24,
                                0x25, 0x18, 0x18 ,0x18,
                                0x18, 0xff, 0xff ,0xff,

};

static char otm1287a_yushun_720p_video_on_cmd8[] = {
				0x3B, 0x00, 0x39, 0xC0,
 				0xE0, 0x00 ,0x03, 0x0B,
                                0x0E, 0x10 ,0x13, 0x17,
                                0x15, 0x2D ,0x3D, 0x51,
                                0x51, 0x5E ,0x75, 0x7C,
                                0x84, 0x94 ,0x9A, 0x98,
                                0xA6, 0xB2 ,0x57, 0x57,
                                0x5A, 0x60 ,0x64, 0x6A,
                                0x72, 0x7F ,0x00, 0x03,
                                0x0B, 0x0E ,0x10, 0x13,
                                0x17, 0x15 ,0x2D, 0x3D,
                                0x51, 0x51 ,0x5E, 0x75,
                                0x7C, 0x84 ,0x94, 0x9A,
                                0x98, 0xA6 ,0xB2, 0x57,
                                0x57, 0x5A ,0x60, 0x64,
                                0x6A, 0x72 ,0x7F, 0xff,
};

static char otm1287a_yushun_720p_video_on_cmd9[] = {
0x03, 0x00, 0x39, 0xC0,
0xB6, 0x4e, 0x4e, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd10[] = {
0x02, 0x00, 0x39, 0xC0,
0xCC, 0x0B, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd11[] = {
0x03, 0x00, 0x39, 0xC0,
0xC0, 0x1F, 0x31, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd12[] = {
0x02, 0x00, 0x39, 0xC0,
0xD2, 0x88, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd13[] = {
0x02, 0x00, 0x39, 0xC0,
0xD4, 0x02, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd14[] = {
0x02, 0x00, 0x39, 0xC0,
0xBD, 0x01, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd15[] = {
0x02, 0x00, 0x39, 0xC0,
0xB1, 0x60, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd16[] = {
0x02, 0x00, 0x39, 0xC0,
0xBD, 0x00, 0xFF, 0xFF,
};

static char otm1287a_yushun_720p_video_on_cmd17[] = {
0x08, 0x00, 0x39, 0xC0,
0xBF, 0x40, 0x81, 0x50,
0x00, 0x1A, 0xFC, 0x01,
};

static char otm1287a_yushun_720p_video_on_cmd18[] = {
0x11, 0x00, 0x05, 0x80,
};

static char otm1287a_yushun_720p_video_on_cmd19[] = {
0x29, 0x00, 0x05, 0x80,
};

static struct mipi_dsi_cmd otm1287a_yushun_720p_video_on_command[] = {


#if 1
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd0, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd1, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd2, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd3, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd4, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd5, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd6, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd7, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd8, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd9, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd10, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd11, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd12, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd13, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd14, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd15, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd16, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd17, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd18, 0),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_on_cmd19, 0),
#endif 
};

#define OTM1287A_YUSHUN_720P_VIDEO_ON_COMMAND ARRAY_SIZE(otm1287a_yushun_720p_video_on_command)

static char otm1287a_yushun_720p_video_off_cmd0[] = {
0x28, 0x00, 0x05, 0x80,
};

static char otm1287a_yushun_720p_video_off_cmd1[] = {
0x10, 0x00, 0x05, 0x80,
};

static struct mipi_dsi_cmd otm1287a_yushun_720p_video_off_command[] = {
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_off_cmd0, 50),
MIPI_DSI_CMD_WAIT(otm1287a_yushun_720p_video_off_cmd1, 120),
};

#define OTM1287A_YUSHUN_720P_VIDEO_OFF_COMMAND ARRAY_SIZE(otm1287a_yushun_720p_video_off_command)

static struct command_state otm1287a_yushun_720p_video_state = {
  0, 1
};

static struct commandpanel_info otm1287a_yushun_720p_video_command_panel = {
  0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

static struct videopanel_info otm1287a_yushun_720p_video_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

static struct lane_configuration otm1287a_yushun_720p_video_lane_config = {
  4, 0, 1, 1, 1, 1, 1
};

static const uint32_t otm1287a_yushun_720p_video_timings[] = {
  // 0x79 ,0x1a ,0x12 ,0x00 ,0x3e ,0x42 ,0x16 ,0x1e ,0x15 ,0x03 ,0x04 ,0x00 
  0x7F, 0x1c, 0x12, 0x00, 0x40, 0x44, 0x16, 0x1e, 0x17, 0x03, 0x04, 0x00
};

static struct panel_timing otm1287a_yushun_720p_video_timing_info = {
    0, 4, 0x04, 0x1b
};

static struct panel_reset_sequence otm1287a_yushun_720p_video_reset_seq = {
 /*** { 1, 0, 1, }, { 20, 20, 20, }, 2*/
  { 1, 0, 1, }, { 20, 1, 20, }, 2
};

static struct backlight otm1287a_yushun_720p_video_backlight = {
    1, 1, 255, 100, 1, "bl_ctrl_pwm"
};

#define OTM1287A_YUSHUN_720P_VIDEO_SIGNATURE    0x1287
#define OTM1287A_YUSHUN_720P_VIDEO_BL_DELAY     20

#endif /*_PANEL_OTM1287A_YITIAN_720P_VIDEO_H_*/

